# Generated by Django 4.0.4 on 2022-05-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_producer',
            field=models.BooleanField(default=False),
        ),
    ]
