# Generated by Django 4.0.4 on 2022-05-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_producer',
            field=models.CharField(choices=[('CONSUMER', 'CONSUMER'), ('PRODUCER', 'PRODUCER')], max_length=8),
        ),
    ]
