# Generated by Django 4.0.4 on 2022-05-14 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_is_producer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_producer',
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_producer', models.CharField(choices=[('CONSUMER', 'CONSUMER'), ('PRODUCER', 'PRODUCER')], max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
