# Generated by Django 4.0.4 on 2022-05-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_is_producer_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_producer',
            new_name='role',
        ),
    ]
