# Generated by Django 4.0.6 on 2022-07-13 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220627_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adress',
            field=models.CharField(db_index=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
