# Generated by Django 4.0.6 on 2022-07-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_adress_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shelf_life',
            field=models.DateField(auto_now=True),
        ),
    ]
