# Generated by Django 4.0.6 on 2022-07-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_shelf_life'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='post',
            name='shelf_life',
            field=models.DateField(),
        ),
    ]
