# Generated by Django 4.0.6 on 2022-08-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_post_product_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='core.product'),
        ),
    ]
