# Generated by Django 4.0.6 on 2022-08-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_cart_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.SlugField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(db_index=True, default=2, max_length=200),
            preserve_default=False,
        ),
    ]
