# Generated by Django 4.0.6 on 2022-08-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_cart_quantity_cart_slug_cart_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='title',
        ),
    ]
