# Generated by Django 4.0.6 on 2022-08-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_cart_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='slug',
        ),
    ]
