# Generated by Django 4.0.6 on 2022-08-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_cart_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.SlugField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
